djpothole/djpothole/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainapp/', include('mainapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/mainapp/home/')),
]

djpothole/mainapp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import RedirectView

app_name = 'mainapp'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('firstlogin/', views.update_ever_logged_in, name='firstLogin'),
    # path('home/<str:id>', views.detail_page, name='detail'),
    path('home/error/pagenotfound/', views.page_not_found,
         name="pageNotFound"),
    path('map/', views.mapview, name='mapview'),
    path('feedback/', views.feedbackview, name='feedbackview'),
    path('list/', views.listview, name='listview'),
    path('list/<str:id>', views.detail_page, name='detail'),
]

djpothole/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UData(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name='u')
    resign_date = models.DateTimeField(null=True, blank=True)

    region = models.CharField(max_length=128)
    ever_logged_in = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

    def update(self):
        self.ever_logged_in = True

djpothole/mainapp/views.py
from django.shortcuts import render
from .models import UData
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView, DetailView
from django.http import HttpResponse
# Create your views here.


def page_not_found(req):
    return render(req, 'mainapp/page_not_found.html')


def detail_page(req, id):
    context = {'id': id}
    return render(req, 'mainapp/detail_page.html', context=context)


@method_decorator(login_required, name="dispatch")
class HomeView(TemplateView):
    template_name = "mainapp/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


def update_ever_logged_in(req):
    current_user = UData.objects.get(user=req.user)
    current_user.ever_logged_in = True
    current_user.save(update_fields=['ever_logged_in'])
    return render(
        req,
        'registration/password_change_done.html',
    )


def mapview(req):
    context = {'user': req.user}
    return render(req, 'mainapp/map_view.html', context=context)


def feedbackview(req):
    return render(
        req,
        'mainapp/feedback_view.html',
    )


def listview(req):
    return render(
        req,
        'mainapp/list_page.html',
    )

djpothole/templates/base.html
<!DOCTYPE html>
{%load static%}
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover-min.css"
    />
  </head>

  <body id="page-top">
    <div id="wrapper" style="font-family:'Montserrat'">
      <nav
        class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-1"
        style="background-color:rgb(123,230,230);background-image: linear-gradient(180deg,rgb(123,230,230) 10%,#224abe);"
      >
        <div
          class="container-fluid d-flex flex-column p-0"
          style="position: absolute;"
        >
          <a
            class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0"
            href="{% url 'mainapp:home' %}"
          >
            <div class="sidebar-brand-text mx-3"><span>SIH</span></div>
          </a>
          <hr class="sidebar-divider my-0" />
          <ul class="nav navbar-nav text-light" id="accordionSidebar">
            <li class="nav-item" role="presentation">
              <a class="nav-link active" href="{% url 'mainapp:home' %}"
                ><span>HOME</span></a
              >
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link active" href="{% url 'mainapp:feedbackview' %}"
                ><span>FEEDBACK</span></a
              >
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link active" href="{% url 'mainapp:listview' %}"
                ><span>REPORTS</span></a
              >
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link active" href="{% url 'mainapp:mapview' %}"
                ><span>MAP</span></a
              >
            </li>
          </ul>
          <div class="text-center d-none d-md-inline">
            <button
              class="btn rounded-circle border-1"
              id="sidebarToggle"
              type="button"
            ></button>
          </div>
        </div>
      </nav>
      <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
          <nav
            class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top"
          >
            <div class="container-fluid">
              <button
                class="btn btn-link d-md-none rounded-circle mr-3"
                id="sidebarToggleTop"
                type="button"
              >
                <i class="fas fa-bars"></i>
              </button>
              <form
                class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
              >
                <div class="input-group">
                  <input
                    class="bg-light form-control border-0 small"
                    type="text"
                    placeholder="Search for ..."
                  />
                  <div class="input-group-append">
                    <button
                      class="btn  py-0"
                      type="button"
                      style="background-color:rgb(123,230,230)"
                    >
                      <i class="fas fa-search"></i>
                    </button>
                  </div>
                </div>
              </form>
              <ul class="nav navbar-nav flex-nowrap ml-auto">
                <li class="nav-item dropdown d-sm-none no-arrow">
                  <a
                    class="dropdown-toggle nav-link"
                    data-toggle="dropdown"
                    aria-expanded="false"
                    href="#"
                    ><i class="fas fa-search"></i
                  ></a>
                  <div
                    class="dropdown-menu dropdown-menu-right p-3 animated--grow-in"
                    role="menu"
                    aria-labelledby="searchDropdown"
                  >
                    <form class="form-inline mr-auto navbar-search w-100">
                      <div class="input-group">
                        <input
                          class="bg-light form-control border-0 small"
                          type="text"
                          placeholder="Search for ..."
                        />
                        <div class="input-group-append">
                          <button class="btn btn-primary py-0" type="button">
                            <i class="fas fa-search"></i>
                          </button>
                        </div>
                      </div>
                    </form>
                  </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1" role="presentation">
                  <div class="nav-item dropdown no-arrow">
                    <a
                      class="dropdown-toggle nav-link"
                      data-toggle="dropdown"
                      aria-expanded="false"
                      href="#"
                      ><span class="badge badge-danger badge-counter">3+</span
                      ><i class="fas fa-bell fa-fw"></i
                    ></a>
                    <div
                      class="dropdown-menu dropdown-menu-right dropdown-list dropdown-menu-right animated--grow-in"
                      role="menu"
                    >
                      <h6
                        style="background-color:rgb(123,230,230);background-image: linear-gradient(270deg,rgb(123,230,230) 10%,#224abe);"
                        class="dropdown-header"
                      >
                        alerts center
                      </h6>

                      <a
                        class="d-flex align-items-center dropdown-item"
                        href="#"
                      >
                      </a
                      ><a
                        class="text-center dropdown-item small text-gray-500"
                        href="#"
                        >Show All Alerts</a
                      >
                    </div>
                  </div>
                </li>

                <div class="d-block topbar-divider"></div>
                <li class="nav-item dropdown no-arrow" role="presentation">
                  <div class="nav-item dropdown no-arrow">
                    <a
                      class="dropdown-toggle nav-link"
                      data-toggle="dropdown"
                      aria-expanded="false"
                      href="#"
                      ><span class="d-none d-lg-inline mr-2 text-gray-600 small"
                        >Hi {{ user.username }}!</span
                      ></a
                    >
                    <div
                      class="dropdown-menu shadow dropdown-menu-right animated--grow-in"
                      role="menu"
                    >
                      <a
                        class="dropdown-item"
                        role="presentation"
                        href="{% url 'password_change' %}"
                        ><i
                          class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"
                        ></i
                        >&nbsp;Change Password</a
                      >

                      <div class="dropdown-divider"></div>
                      <a
                        class="dropdown-item"
                        role="presentation"
                        href="{% url 'logout' %}"
                        ><i
                          class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                        ></i
                        >&nbsp;Logout</a
                      >
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
        </div>

        <main>
          <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-app.js"></script>
          <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-firestore.js"></script>
          <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-storage.js"></script>
          <!-- TODO: Add SDKs for Firebase products that you want to use
                     https://firebase.google.com/docs/web/setup#available-libraries -->
          <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-analytics.js"></script>
        </main>
        {% block content %} {% endblock %}

        <footer class="bg-dark footer-dark sticky-footer">
          <div class="container my-auto col-lg-12 col-xl-12">
            <div class="text-center my-auto copyright">
              <span>Copyright © zahanat&nbsp;</span>
            </div>
          </div>
        </footer>
      </div>
      <a class="border rounded d-inline scroll-to-top" href="#page-top"
        ><i class="fas fa-angle-up"></i
      ></a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'js/theme.js' %}"></script>
  </body>
</html>

djpothole/templates/mainapp/changePass.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body></body>
</html>

djpothole/templates/mainapp/detail_page.html
{% extends 'base.html' %} {% load static %}{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Detail</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <script>
      var id = "{{ id }}";
    </script>
    <div
      class="card-body col-lg-8 col-md-8 col-mb-10 align-self-center jumbotron "
      style="background-color:#dcebfa"
    >
      <h4>POTHOLE ID:</h4>
      <h5>{{ id }}</h5>
      <script src="{% static 'js/firebaseinit.js' %}"></script>
      <div class="row" style="margin-bottom:15px">
        <div class="col-lg-6 col-xl-7 align-self-center">
          <img id="image" width="200" height="200" />
        </div>
        <div class="col-lg-6 col-xl-5 " style="margin-top:10px">
          <ul style="list-style-type:none">
            <li><div id="landmark"></div></li>
            <li><div id="location"></div></li>
            <li><div id="occurrence"></div></li>
            <li><div id="region"></div></li>
            <li><div id="status"></div></li>
            <li><div id="timestamp"></div></li>
            <li><div id="uid"></div></li>
          </ul>
        </div>
      </div>
      <script src="{% static 'js/button.js' %}"></script>
      <div class="row justify-content-center ">
        <button
          class="btn-success hvr-shrink "
          onclick="workingButton(); dis()"
          id="accept"
          type="submit"
          style="visibility: hidden;"
        >
          <div>ACCEPT REPORT</div>
        </button>
        <div style="margin-right:10px; margin-left:10px"></div>
        <button
          class="btn-primary hvr-shrink"
          onclick="completeButton(); dis()"
          id="complete"
          type="submit"
          style="visibility: hidden;"
        >
          <div>COMPLETE REPORT</div>
        </button>
      </div>
    </div>
    <script src="{% static 'js/firebaseDetail.js' %}" onload="dis()"></script>
  </body>
  {% else %}
  <script>
    window.location.href = "{% url 'login' %}";
  </script>
  {% endif %}
</html>
{% endblock %}

djpothole/templates/mainapp/feedback_view.html
{% extends 'base.html' %} {% load static %} {% block title %}FEEDBACK{% endblock %} {% block content %} {% if user.is_authenticated %}
<script src="{% static 'js/firebaseinit.js' %}"></script>
<link href="./feedback.css" />
<script>
  var b = "{{user.u.ever_logged_in}}";
  if (b == "False") {
    window.location.href = "{% url 'password_change' %}";
  }
  var user = "{{user.u.region}}";
  var fdb = db.collection("reports");
  fdb.where("status", "in", ["Completed"]).onSnapshot(querySnapshot => {
    const documents = [];
    querySnapshot.forEach(doc => {
      const d = doc;
      documents.push(d);
    });
    var a = document.getElementById("test");
    var filteredDocuments = documents.filter(docu => {
      return docu
        .data()
        .region.toLowerCase()
        .includes(user.toLowerCase());
    });

    var fback = document.getElementById("feedback");
     while (fback.hasChildNodes()) {
       fback.removeChild(fback.firstChild);
     }

    filteredDocuments.forEach(doc => {
      var li = document.createElement("div");
      li.className = "card-body";
      li.innerHTML = `<div style="color:white; background-color:#4285f4; box-shadow:3px 3px 3px 3px;  border-radius: 25px;  padding:20px;  cursor:pointer; data-toggle="tooltip" title="feedback from ${
        doc.id
      }"><h2>Report ID:${doc.id}</h2><br><h3>Feedback:${
        doc.data().feedback
      }</h3><div>`;
      fback.appendChild(li);
    });

    //fback.appendChild(fbackchild);
  });
</script>
<div
  style=" margin: auto; width:100%;height:100%;"
  id="feedback"
  class="bg-gradient-info"
></div>
{% else %}
<script>
  window.location.href = "{% url 'login' %}";
</script>
{% endif %} {% endblock %}

djpothole/templates/mainapp/home.html
{% extends 'base.html' %} {% load static %} {% block title %}Home{% endblock %}
{% block content %} {% if user.is_authenticated %}
<link
  rel="stylesheet"
  href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""
/>
<script>
  var b = "{{user.u.ever_logged_in}}";
  if (b == "False") {
    window.location.href = "{% url 'password_change' %}";
  }
</script>
<link
  rel="stylesheet"
  href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""
/>
<script
  src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
  crossorigin=""
></script>

<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<div class="container-fluid">
  <div class="d-sm-flex justify-content-between align-items-center mb-4">
    <h3 class="text-dark mb-0">Dashboard</h3>
  </div>
  <div class="row">
    <div class=" mb-4 col-lg-4 col-xl-4 col-md-12 hvr-shrink">
      <div class="card shadow border-left-primary py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col mr-2">
              <div
                class="text-uppercase text-primary font-weight-bold text-xs mb-1"
              >
                <span>reports</span>
              </div>
              <div class="text-dark font-weight-bold h5 mb-0">
                <span id="total"></span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class=" mb-4 col-lg-4 col-xl-4 col-md-12 hvr-shrink">
      <div class="card shadow border-left-success py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col mr-2">
              <div
                class="text-uppercase text-success font-weight-bold text-xs mb-1"
              >
                <span>completed</span>
              </div>
              <div class="text-dark font-weight-bold h5 mb-0">
                <span id="completed"></span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-check fa-2x text-gray-300 "></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class=" mb-4 col-lg-4 col-xl-4 col-md-12 hvr-shrink">
      <div class="card shadow border-left-warning py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col mr-2">
              <div
                class="text-uppercase text-warning font-weight-bold text-xs mb-1"
              >
                <span>Pending reports</span>
              </div>
              <div class="text-dark font-weight-bold h5 mb-0">
                <span id="pending"></span>
              </div>
            </div>
            <div class="col-auto">
              <i
                class="fas fa-comments fa-2x text-gray-300 fas fa-exclamation-circle"
              ></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-7 col-xl-8 ">
      <!-- <a href="/mainapp/map"> -->
      <div class="card shadow mb-4">
        <div
          class="card-header d-flex justify-content-between align-items-center"
        >
          <h6 class="text-primary font-weight-bold m-0">POTHOLE</h6>
        </div>
        <div class="card-body">
          <link
            rel="stylesheet"
            href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
            integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
            crossorigin=""
          />
          <script
            src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
            integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
            crossorigin=""
          ></script>

          <div id="mapid"></div>
        </div>
        <style>
          #mapid {
            height: 365px;
          }
        </style>
        <script>
          var user = "{{user.u.region}}";
        </script>
        <!-- </a> -->
      </div>
    </div>

    <div class="col-lg-5 col-xl-4 hvr-shrink ">
      <div class="card shadow mb-4">
        <div
          class="card-header d-flex justify-content-between align-items-center"
        >
          <h6 class=" text-primary font-weight-bold m-0">CHART</h6>
        </div>
        <div class="card-body">
          <div class="chart-area"><canvas id="chartcanvas"></canvas></div>
          <div class="text-center small mt-4">
            <span class="mr-2"
              ><i class="fas fa-circle text-success"></i
              >&nbsp;COMPLETED/RESOLVED</span
            >
            <span class="mr-2"
              ><i class="fas fa-circle" style="color: #f6c23e"></i
              >&nbsp;PENDING</span
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="list-group">
  <div id="test" onload="setList()"></div>
</div>
<script>
  var user = "{{ user.u.region }}";
  var fd = [];
  var potholeMarker = L.icon({
    iconUrl: "{% static 'img/icon.png' %}",
    iconSize: [60],
    iconAnchor: [20, 20]
  });

  var ctx = document.getElementById("chartcanvas").getContext("2d");
  var chart = new Chart(ctx, {
    type: "doughnut",
    data: {
      labels: ["resolved", "pending"],
      datasets: [
        {
          label: "",
          backgroundColor: ["#1cc88a", "#f6c23e"],
          borderColor: ["#ffffff", "#ffffff"],
          data: ["0", "0"]
        }
      ]
    },
    options: {
      maintainAspectRatio: false,
      legend: {
        display: false
      },
      title: {}
    }
  });
</script>

<script src="{% static 'js/firebaseinit.js' %}"></script>
<script src="{% static 'js/firebaseMap.js' %}"></script>

<script src="{% static 'js/firebase.js' %}"></script>
{% else %}
<script>
  window.location.href = "{% url 'login' %}";
</script>
{% endif %} {% endblock %}

djpothole/templates/mainapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <div id="test"></div>
    <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-firestore.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
    <script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-analytics.js"></script>
    <script>
      var users = "{{ user.u.region }}";
    </script>
    <script src="{% static 'js/firebase.js' %}"></script>
  </body>
</html>

djpothole/templates/mainapp/list_page.html
{% extends 'base.html' %} {% load static %} {% block title %}LIST{% endblock %}
{% block content %} {% if user.is_authenticated %}
<script src="{% static 'js/firebaseinit.js' %}"></script>
<link href="./feedback.css" />
<script>
  var b = "{{user.u.ever_logged_in}}";
  if (b == "False") {
    window.location.href = "{% url 'password_change' %}";
  }
  var user = "{{user.u.region}}";
  var fdb = db.collection("reports");
  fdb
    .where("status", "in", ["Reported", "Working"])
    .onSnapshot(querySnapshot => {
      const documents = [];
      querySnapshot.forEach(doc => {
        const d = doc;
        documents.push(d);
      });
      var filteredDocuments = documents.filter(docu => {
        return docu
          .data()
          .region.toLowerCase()
          .includes(user.toLowerCase());
      });

      filteredDocuments.sort((a, b) => {
        return b.data().occurrence - a.data().occurrence;
      });

      var fback = document.getElementById("list");
      while (fback.hasChildNodes()) {
        fback.removeChild(fback.firstChild);
      }

      filteredDocuments.forEach(doc => {
        var li = document.createElement("div");
        var a = document.createElement("a");
        li.className = "card-body";
        a.innerHTML = `<div style="color:white; background-color:#4285f4; box-shadow:3px 3px 3px 3px;  border-radius: 25px;  padding:20px;  cursor:pointer; data-toggle="tooltip" title="Report from ${doc.id}"><h2>Report ID:${doc.id}</h2><div>`;
        a.href = "" + doc.id;
        a.style = "text-decoration: none;";
        li.appendChild(a);
        fback.appendChild(li);
      });

      //fback.appendChild(fbackchild);
    });
</script>
<div
  style=" margin: auto; width:100%;height:100%;"
  id="list"
  class="bg-gradient-info"
></div>
{% else %}
<script>
  window.location.href = "{% url 'login' %}";
</script>
{% endif %} {% endblock %}

djpothole/templates/mainapp/map_view.html
{% extends 'base.html' %} {% load static %} {% block title %}MAP{% endblock %}
{% block content %}
{% if user.is_authenticated %}

<script>
  var b = "{{user.u.ever_logged_in}}";
  if (b == "False") {
    window.location.href = "{% url 'password_change' %}";
  }
</script>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
   integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
   crossorigin=""></script>

<div class="jumbotron" id="mapid"></div>
<script src="{% static 'js/firebaseinit.js' %}"></script>
<script src="{% static 'js/firebaseMap.js' %}"></script>
<style>#mapid { height: 600px;
 margin-left: 10px;margin-bottom: 30px;margin-right:10px; }
</style>
<script>
    var user="{{user.u.region}}"
    var fd=[];
    var potholeMarker=L.icon({
    iconUrl: "{% static 'img/icon.png' %}",
    iconSize: [60],
    iconAnchor: [20, 20]
    })
</script>
{% else %}
<script>
  window.location.href = "{% url 'login' %}";
</script>
{% endif %}
{% endblock %}

djpothole/templates/mainapp/page_not_found.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <h1>Page Not Found!</h1>
  </body>
</html>